account/urls.py
from django.urls import path

from account.views import sign_up, sign_in, log_out, add_history, add_favorite, change_profile

app_name = "account"
urlpatterns = [
    path('register/', sign_up, name='sign_up'),
    path('login/', sign_in, name='sign_in'),
    path('logout/', log_out, name='log_out'),
    path('change_profile/', change_profile, name='change_profile'),
    path('ajax/add_history/', add_history, name='add_history'),
    path('ajax/add_favorite/', add_favorite, name='add_favorite'),
]

musicApp/urls.py
from django.urls import path

from musicApp.views import HomePageView, search, ArtistDetailView, ArtistListView, EventDetailView, GenreListView, \
    SongDetailView, TopChartListView, NewReleaseListView, ClassicListView, AlbumListView, PlaylistListView, \
    AlbumDetailView, init_songs, get_playlist_songs, get_genre_songs, get_singer_songs, get_album_songs, \
    FreeMusicListView, increment_music_play, HistoryListView, FavoriteListView, SettingTemplateView, PlanTemplateView, \
    ProfileTemplateView

app_name = "musicApp"
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('artist/<int:pk>/', ArtistDetailView.as_view(), name='artist_detail'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('song/<int:pk>/', SongDetailView.as_view(), name='song_detail'),
    path('album/<int:pk>/', AlbumDetailView.as_view(), name='album_detail'),
    path('artists/', ArtistListView.as_view(), name='artists'),
    path('genres/', GenreListView.as_view(), name='genres'),
    path('songs/top_chart/', TopChartListView.as_view(), name='songs_top_chart'),
    path('songs/new_release/', NewReleaseListView.as_view(), name='songs_new_release'),
    path('songs/classic/', ClassicListView.as_view(), name='songs_classic'),
    path('albums/', AlbumListView.as_view(), name='albums'),
    path('songs/free', FreeMusicListView.as_view(), name='songs_free'),
    path('playlists/', PlaylistListView.as_view(), name='playlists'),
    path('favorites/', FavoriteListView.as_view(), name='favorites'),
    path('history/', HistoryListView.as_view(), name='history'),
    path('setting/', SettingTemplateView.as_view(), name='setting'),
    path('plan/', PlanTemplateView.as_view(), name='plan'),
    path('profile/', ProfileTemplateView.as_view(), name='profile'),
    path('ajax/search/', search, name='search'),
    path('ajax/init_songs/', init_songs, name='init_songs'),
    path('ajax/get_playlist_songs/', get_playlist_songs, name='get_playlist_songs'),
    path('ajax/get_genre_songs/', get_genre_songs, name='get_genre_songs'),
    path('ajax/get_singer_songs/', get_singer_songs, name='get_singer_songs'),
    path('ajax/get_album_songs/', get_album_songs, name='get_album_songs'),
    path('ajax/increment_plays/', increment_music_play, name='increment_plays'),
]

radioamin/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import musicApp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('musicApp.urls')),
    path('account/', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL,
                           document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

account/models.py
from django.contrib.auth.models import User
from django.db import models


def user_directory_path(instance, filename):
    return '{0}/{1}/{2}'.format('user', instance.user.email, filename)


class MusicAppAccount(models.Model):
    PLAN_BASIC = 1
    PLAN_PRIME = 2
    plan_choices = [
        (PLAN_BASIC, 'basic'),
        (PLAN_PRIME, 'prime'),
    ]

    STREAM_QUALITY_320 = 320
    STREAM_QUALITY_128 = 128
    stream_quality_choices = [
        (STREAM_QUALITY_320, '320kb'),
        (STREAM_QUALITY_128, '128kb'),
    ]

    user = models.OneToOneField(User, on_delete=models.PROTECT)
    display_name = models.CharField(max_length=25, blank=True)
    location = models.CharField(max_length=25, blank=True)
    about = models.TextField(blank=True)
    avatar = models.ImageField(upload_to=user_directory_path,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    plan = models.PositiveIntegerField(choices=plan_choices, default=1)
    plan_expire = models.DateTimeField(blank=True, null=True)
    setting_get_email = models.BooleanField(default=True)
    setting_get_sms = models.BooleanField(default=False)
    setting_normalize_volume = models.BooleanField(default=True)
    setting_stream_quality = models.PositiveIntegerField(choices=stream_quality_choices, default=320)
    setting_theme_night_mode = models.BooleanField(default=False)
    favorite = models.ManyToManyField('musicApp.Music', blank=True)
    history = models.ManyToManyField('musicApp.Music', related_name='user_history', blank=True)

    def __str__(self):
        return self.user.email

musicApp/models.py
from django.db import models
from datetime import timedelta, date


def music_directory_path(instance, filename):
    return '{0}/{1}/{2}/{3}'.format(instance.singer, instance.album.name, instance.name, filename)


def album_directory_path(instance, filename):
    return '{0}/{1}/{2}'.format(instance.singer, instance.name, filename)


def playlist_directory_path(instance, filename):
    return '{0}/{1}/{2}'.format('playlist', instance.name, filename)


def singer_directory_path(instance, filename):
    return '{0}/{1}'.format(instance.name, filename)


def event_directory_path(instance, filename):
    return '{0}/{1}/{2}'.format('event', instance.name, filename)


def genre_directory_path(instance, filename):
    return '{0}/{1}/{2}'.format('genre', instance.name, filename)


class Music(models.Model):
    name = models.CharField(max_length=50, null=False, default='Unnamed')
    singer = models.ForeignKey('Singer', on_delete=models.CASCADE, null=False)
    genre = models.ManyToManyField('Genre')
    album = models.ForeignKey('Album', on_delete=models.CASCADE)
    pub_date = models.DateField(auto_now_add=True)
    plays = models.PositiveIntegerField(default=0)
    lyrics = models.TextField(null=True, blank=True)
    music = models.CharField(max_length=50, null=True, blank=True)
    song_writer = models.CharField(max_length=50, null=True, blank=True)
    arrangement = models.CharField(max_length=50, null=True, blank=True)
    mix_mastering = models.CharField(max_length=50, null=True, blank=True)
    cover_art = models.CharField(max_length=50, null=True, blank=True)
    top_chart = models.BooleanField(default=False)
    premium = models.BooleanField(default=False)
    song = models.FileField(upload_to=music_directory_path)
    cover = models.ImageField(upload_to=music_directory_path, blank=True, default='default_320_320')

    def __str__(self):
        return self.name


class MusicPlay(models.Model):
    music = models.ForeignKey('Music', on_delete=models.CASCADE)
    datePlay = models.DateField()
    plays = models.PositiveIntegerField(default=0)

    @staticmethod
    def increment_play(music, date_today):
        try:
            mPlay = MusicPlay.objects.get(datePlay=date_today - timedelta(days=7), music=music)
            mPlay.datePlay = date_today
            mPlay.plays += 1
            mPlay.save()

        except MusicPlay.DoesNotExist:
            try:
                mPlay = MusicPlay.objects.get(datePlay=date_today, music=music)
                mPlay.plays += 1
                mPlay.save()
            except MusicPlay.DoesNotExist:
                mPlay = MusicPlay(music=music, datePlay=date_today, plays=1)
                mPlay.save()

    def __str__(self):
        return '{0}/{1}/{2}'.format(self.music, self.datePlay, self.plays)


class Genre(models.Model):
    name = models.CharField(max_length=50, null=False, default='Unnamed')
    cover = models.ImageField(upload_to=genre_directory_path, blank=True, default='default_540_320.jpg')

    def __str__(self):
        return self.name


class Singer(models.Model):
    name = models.CharField(max_length=50, null=False, default='Unknown')
    biography = models.TextField(null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    follows = models.PositiveIntegerField(default=0)
    featured = models.BooleanField(default=False)
    cover = models.ImageField(upload_to=singer_directory_path, blank=True, default='default_320_320')

    def __str__(self):
        return self.name


class Album(models.Model):
    name = models.CharField(max_length=50, null=False, default='Unnamed')
    pub_date = models.DateField(null=True, blank=True)
    singer = models.ForeignKey('Singer', on_delete=models.CASCADE)
    cover = models.ImageField(upload_to=album_directory_path, blank=True, default='default_320_320')

    def __str__(self):
        return '{0} / {1}'.format(self.singer, self.name)


class Playlist(models.Model):
    name = models.CharField(max_length=50, null=False, default='Unnamed')
    cover = models.ImageField(upload_to=playlist_directory_path, blank=True, default='default_540_320')
    songs = models.ManyToManyField('Music')

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=50, null=False, default='Unnamed')
    info = models.TextField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=20, null=False)
    email = models.EmailField(null=True, blank=True)
    due_time = models.DateTimeField()
    image = models.ImageField(upload_to=event_directory_path, blank=True)
    background_image = models.ImageField(upload_to=event_directory_path)

    def __str__(self):
        return self.name

templates/musicApp/album_detail.html
{% extends "musicApp/base.html" %}
{% block content %}
    <!-- Begin | Main Container [[ Find at scss/base/core.scss ]] -->
    <div class="main-container" id="appRoute">
        <div class="row section text-center text-md-left">
            <div class="col-xl-3 col-lg-4 col-sm-5">
                <img src="{{ album.cover.url }}" alt="" class="card-img--radius-lg">
            </div>
            <div class="col-xl-9 col-lg-8 col-sm-7">
                <div class="row pt-4">
                    <div class="col-xl-8 col-lg-6">
                        <h5 class="album-name">{{ album.name }}</h5>
                        <p>{{ album.singer.name }}</p>
                        <div class="text-warning stars">
                            <i class="la la-star"></i>
                            <i class="la la-star"></i>
                            <i class="la la-star"></i>
                            <i class="la la-star"></i>
                            <i class="la la-star-half-empty"></i>
                        </div>
                        <div class="mt-4">
                            <a href="javascript:void(0);" class="btn btn-pill btn-air btn-bold btn-danger play-all">Play
                                All</a>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-6">
                        <div class="pt-3 pt-lg-0 text-lg-right">
                            <button class="btn btn-pill btn-air btn-danger btn-icon-only"><i class="la la-heart-o"></i>
                            </button>
                            <button class="btn btn-pill btn-air btn-brand btn-icon-only"><i class="la la-share-alt"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Begin | Section [[ Find at scss/base/core.scss ]] -->
        <div class="section">
            <!-- Begin | Line Tabs [[ Find at scss/framework/components/line-tabs.scss ]] -->
            <ul class="nav nav-tabs line-tabs line-tabs-primary text-uppercase mb-4" id="artistDetails" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="song-tab" data-toggle="tab" href="#song" role="tab"
                       aria-controls="song"
                       aria-selected="true">Top Songs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="bio-tab" data-toggle="tab" href="#bio" role="tab" aria-controls="bio"
                       aria-selected="false">Info</a>
                </li>
            </ul>
            <!-- End | Line Tabs -->

            <!-- Begin | Tab Content -->
            <div class="tab-content" id="artistDetailsContent">
                <div class="tab-pane fade show active" id="song" role="tabpanel" aria-labelledby="song-tab">
                    <div class="row align-items-end">
                        <span class="col-6 font-weight-bold">{{ tracks.count }} Track</span>
                        <div class="col-6 ml-auto">
                            <form action="#" class="form-inline justify-content-end">
                                <label class="mr-2" for="filter1">Sorted By:</label>
                                <select class="custom-select mr-sm-2" id="filter1">
                                    <option selected>Popular</option>
                                    <option value="1">A-Z</option>
                                    <option value="2">Z-A</option>
                                </select>
                            </form>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <!-- Begin | Custom List [[ Find at scss/framework/components/custom-list.scss ]] -->
                    <div class="custom-list">
                        {% for track in album.music_set.all %}
                            <!-- Begin | Custom List Item -->
                            <div class="custom-list--item">
                                <div class="text-dark custom-card--inline data-audio"
                                     data-audio='{"name": "{{ track.name }}", "artist": "{{ track.singer.name }}", "album": "{{ track.album }}", "url": "{{ track.song.url }}", "cover_art_url": "{{ track.cover.url }}"}'>
                                    <div class="custom-card--inline-img">
                                        <img src="{{ track.cover.url }}" alt="" class="card-img--radius-sm">
                                    </div>

                                    <div class="custom-card--inline-desc">
                                        <p class="text-truncate mb-0">{{ track.name }}</p>
                                        <p class="text-truncate text-muted font-sm">{{ track.album.name }}</p>
                                    </div>
                                </div>
                                <ul class="custom-card--labels d-flex ml-auto">
                                    <li class="dropleft">
                                        <a href="javascript:void(0);" class="btn btn-icon-only p-0 w-auto h-auto"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="la la-ellipsis-h"></i>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li class="dropdown-item">
                                                <a href="javascript:void(0);" class="dropdown-link favorite">
                                                    <i class="la la-heart-o"></i>
                                                    <span>Favorite</span>
                                                </a>
                                            </li>
                                            <li class="dropdown-item">
                                                <a href="javascript:void(0);" class="dropdown-link">
                                                    <i class="la la-plus"></i>
                                                    <span>Add to Playlist</span>
                                                </a>
                                            </li>
                                            <li class="dropdown-item">
                                                <a href="javascript:void(0);" class="dropdown-link">
                                                    <i class="la la-download"></i>
                                                    <span>Download</span>
                                                </a>
                                            </li>
                                            <li class="dropdown-item">
                                                <a href="javascript:void(0);" class="dropdown-link">
                                                    <i class="la la-share-alt"></i>
                                                    <span>Share</span>
                                                </a>
                                            </li>
                                            <li class="dropdown-item">
                                                <a href="song-details.html" class="dropdown-link">
                                                    <i class="la la-info-circle"></i>
                                                    <span>Song Info</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                            <!-- End | Custom List Item -->
                        {% endfor %}
                    </div>
                    <!-- End | Custom List -->
                </div>
                <div class="tab-pane fade show" id="album" role="tabpanel" aria-labelledby="album-tab">
                    <div class="row align-items-end">
                        <span class="col-6 font-weight-bold">{{ albums.count }} Album</span>
                        <div class="col-6 ml-auto">
                            <form action="#" class="form-inline justify-content-end">
                                <label class="mr-2" for="filter2">Sorted By:</label>
                                <select class="custom-select mr-sm-2" id="filter2">
                                    <option selected>Popular</option>
                                    <option value="1">A-Z</option>
                                    <option value="2">Z-A</option>
                                </select>
                            </form>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <!-- Begin | Custom List [[ Find at scss/framework/components/custom-list.scss ]] -->
                    <div class="custom-list">
                        {% for album in albums %}
                            <!-- Begin | Custom List Item -->
                            <div class="custom-list--item">
                                <div class="text-dark custom-card--inline">
                                    <div class="custom-card--inline-img">
                                        <img src="{{ album.cover.url }}" alt="" class="card-img--radius-sm">
                                    </div>

                                    <div class="custom-card--inline-desc">
                                        <p class="text-truncate mb-0">{{ album.name }}</p>
                                        <p class="text-truncate text-muted font-sm">{{ album.singer.name }}</p>
                                    </div>
                                </div>
                                <ul class="custom-card--labels d-flex ml-auto">
                                    <li><span class="badge badge-pill badge-danger"><i class="la la-heart"></i></span>
                                    </li>
                                    <li class="dropleft">
                                        <a href="javascript:void(0);" class="btn btn-icon-only p-0 w-auto h-auto"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="la la-ellipsis-h"></i>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li class="dropdown-item">
                                                <a href="javascript:void(0);" class="dropdown-link favorite">
                                                    <i class="la la-heart-o"></i>
                                                    <span>Favorite</span>
                                                </a>
                                            </li>
                                            <li class="dropdown-item">
                                                <a href="javascript:void(0);" class="dropdown-link">
                                                    <i class="la la-plus"></i>
                                                    <span>Add to Playlist</span>
                                                </a>
                                            </li>
                                            <li class="dropdown-item">
                                                <a href="javascript:void(0);" class="dropdown-link">
                                                    <i class="la la-download"></i>
                                                    <span>Download</span>
                                                </a>
                                            </li>
                                            <li class="dropdown-item">
                                                <a href="javascript:void(0);" class="dropdown-link">
                                                    <i class="la la-share-alt"></i>
                                                    <span>Share</span>
                                                </a>
                                            </li>
                                            <li class="dropdown-item">
                                                <a href="song-details.html" class="dropdown-link">
                                                    <i class="la la-info-circle"></i>
                                                    <span>Song Info</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                            <!-- End | Custom List Item -->
                        {% endfor %}
                    </div>
                    <!-- End | Custom List -->
                </div>
                <div class="tab-pane fade show" id="bio" role="tabpanel" aria-labelledby="bio-tab">
                    <p>{{ album.pub_date }}</p>
                </div>
            </div>
            <!-- End | Tab Content -->
        </div>
        <!-- End | Section -->

    </div>
    <!-- End | Main Container -->
{% endblock content %}

templates/musicApp/album_list.html
{% extends "musicApp/base.html" %}
{% block content %}
    <!-- Begin | Main Container [[ Find at scss/base/core.scss ]] -->
    <div class="main-container" id="appRoute">

        <div class="row align-items-end">
            <span class="col-6 font-weight-bold">{{ album_list.count }} Results</span>
            <div class="col-6 ml-auto">
                <form action="#" class="form-inline justify-content-end">
                    <label class="mr-2" for="filter2">Sorted By:</label>
                    <select class="custom-select mr-sm-2" id="filter2">
                        <option selected>Popular</option>
                        <option value="1">A-Z</option>
                        <option value="2">Z-A</option>
                    </select>
                </form>
            </div>
            <div class="col-12">
                <hr>
            </div>
        </div>

        <div class="row section">
            {% for album in album_list %}
                <div class="col-xl-3 col-lg-4 col-sm-6 pb-4">
                    <div class="custom-card">
                        <div class="custom-card--img">
                            <div class="custom-card--info">
                                <ul class="custom-card--labels d-flex">
                                    <li><span class="badge badge-pill badge-warning"><i class="la la-star"></i></span>
                                    </li>
                                </ul>
                                <div class="dropdown dropdown-icon">
                                    <a href="javascript:void(0);" role="button" data-toggle="dropdown"
                                       aria-haspopup="true" aria-expanded="false">
                                        <i class="ion-md-more"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li class="dropdown-item">
                                            <a href="javascript:void(0);" class="dropdown-link favorite">
                                                <i class="la la-heart-o"></i>
                                            </a>
                                        </li>
                                        <li class="dropdown-item">
                                            <a href="javascript:void(0);" class="dropdown-link">
                                                <i class="la la-plus"></i>
                                            </a>
                                        </li>
                                        <li class="dropdown-item">
                                            <a href="javascript:void(0);" class="dropdown-link">
                                                <i class="la la-download"></i>
                                            </a>
                                        </li>
                                        <li class="dropdown-item">
                                            <a href="javascript:void(0);" class="dropdown-link">
                                                <i class="la la-share-alt"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <a href="{% url 'musicApp:album_detail' pk=album.pk %}">
                                <img src="{{ album.cover.url }}" alt="{{ album.name }}" class="card-img--radius-lg">
                            </a>
                        </div>

                        <a href="{% url 'musicApp:album_detail' pk=album.pk %}" class="custom-card--link mt-2">
                            <h6>{{ album.name }}</h6>
                            <p>{{ album.singer.name }}</p>
                        </a>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
    <!-- End | Main Container -->
{% endblock content %}

templates/musicApp/event_detail.html
{% extends "musicApp/base.html" %}
{% block content %}
    <!-- Begin | Main Container [[ Find at scss/base/core.scss ]] -->
    <div class="main-container" id="appRoute">

        <div class="section">
            <div class="heading">
                <div class="d-flex flex-wrap align-items-end">
                    <div class="flex-grow-1">
                        <h4>{{ event.name }}</h4>
                        <p>Public Event</p>
                    </div>
                    <a href="songs.html" class="btn btn-bold btn-pill btn-air btn-warning">Buy now</a>
                </div>
                <hr>
            </div>
            <div class="row">
                <div class="col-sm-5">
                    <div class="event event-h bg-img bg-img-radius-lg mb-4"
                         style="background-image: url('{{ event.background_image.url }}')"></div>
                    <div class="mb-3">
                        <b>Venue At</b>
                        <p>{{ event.address }}</p>
                    </div>
                    <div class="mb-3">
                        <b>Phone Number</b>
                        <p>{{ event.phone }}</p>
                    </div>
                    <div class="mb-3">
                        <b>Email ID</b>
                        <p>{{ event.email }}</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <p>{{ event.info }}</p>
                </div>
            </div>
        </div>

    </div>
    <!-- End | Main Container -->
{% endblock content %}

templates/musicApp/singer_list.html
{% extends "musicApp/base.html" %}
{% block content %}
    <!-- Begin | Main Container [[ Find at scss/base/core.scss ]] -->
    <div class="main-container" id="appRoute">

        <div class="row align-items-end">
            <span class="col-6 font-weight-bold">{{ singer_list.count }} Results</span>
            <div class="col-6 ml-auto">
                <form action="#" class="form-inline justify-content-end">
                    <label class="mr-2" for="filter2">Sorted By:</label>
                    <select class="custom-select mr-sm-2" id="filter2">
                        <option selected>Popular</option>
                        <option value="1">A-Z</option>
                        <option value="2">Z-A</option>
                    </select>
                </form>
            </div>
            <div class="col-12">
                <hr>
            </div>
        </div>

        <div class="row section">
            {% for artist in singer_list %}
                <div class="col-xl-3 col-lg-4 col-sm-6 pb-4">
                    <div class="custom-card">
                        <div class="custom-card--img">
                            <a href="{% url 'musicApp:artist_detail' pk=artist.pk %}">
                                <img src="{{ artist.cover.url }}" alt="{{ artist.name }}" class="card-img--radius-lg">
                            </a>
                        </div>

                        <a href="{% url 'musicApp:artist_detail' pk=artist.pk %}" class="custom-card--link mt-2">
                            <h6 class="mb-0">{{ artist.name }}</h6>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
    <!-- End | Main Container -->
{% endblock content %}